server:
  port: 7000

spring:
  application:
    name: usuario
  cloud:
    config:
      uri: http://localhost:8888
  profiles:
    active: dev
  datasource:
    username: pedrolop90
    password: pedrolop90
    url: jdbc:mysql://testing-1.c2it6rxhlefj.us-east-1.rds.amazonaws.com:3306/testing
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      max_allowed_packet: 2000
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic